In [1]:
import math
import numpy as np
import torch
from torch import nn
from d2l import torch as d2l

c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.7.0) or chardet (7.4.3)/charset_normalizer (3.4.7) doesn't match a supported version!
  warnings.warn(


In [5]:
max_degree=20 #多项式的最大阶数
n_train,n_test=100,100 #训练和测试数据集大小
true_w=np.zeros(max_degree)
true_w[0:4]=np.array([5,1.2,-3.4,5.6])

features=np.random.normal(size=(n_train+n_test,1))
np.random.shuffle(features)
poly_features=np.power(features,np.arange(max_degree).reshape(1,-1))
for i in range(max_degree):
    poly_features[:,i]/=math.gamma(i+1) #gamma(n)=(n-1)!
#labels的维度:(n_train+n_test,)
labels=np.dot(poly_features,true_w)
labels+=np.random.normal(scale=0.1,size=labels.shape)

In [7]:
# NumPy ndarray转换为tensor
true_w, features, poly_features, labels = [torch.tensor(x, dtype=
    torch.float32) for x in [true_w, features, poly_features, labels]]

In [8]:
features[:2],poly_features[:2,:],labels[:2]

(tensor([[0.7142],
         [1.2003]]),
 tensor([[1.0000e+00, 7.1424e-01, 2.5507e-01, 6.0726e-02, 1.0843e-02, 1.5489e-03,
          1.8438e-04, 1.8813e-05, 1.6796e-06, 1.3329e-07, 9.5204e-09, 6.1817e-10,
          3.6793e-11, 2.0215e-12, 1.0313e-13, 4.9105e-15, 2.1920e-16, 9.2097e-18,
          3.6544e-19, 1.3737e-20],
         [1.0000e+00, 1.2003e+00, 7.2040e-01, 2.8824e-01, 8.6496e-02, 2.0765e-02,
          4.1541e-03, 7.1234e-04, 1.0688e-04, 1.4255e-05, 1.7110e-06, 1.8671e-07,
          1.8676e-08, 1.7244e-09, 1.4785e-10, 1.1831e-11, 8.8760e-13, 6.2671e-14,
          4.1793e-15, 2.6403e-16]]),
 tensor([5.3531, 5.6540]))